#!/usr/bin/python3

import RPi.GPIO as GPIO
import time
import os
from contextlib import ExitStack
from MQTTClient import MQTTClient
from PressureSensor import PressureSensor
from DataPublisher import DataPublisher
import configparser

# Setup GPIO
GPIO.setmode(GPIO.BCM)

# GPIO INPUT PINS
# GPIO 2 and 3 (pins 3 and 5) are used for I2C
# 
FIRE_FLOW = 17             # Pin 11
HOUSE_FLOW_PULSE = 27      # Pin 13
IRRIGATION_FLOW_PULSE = 22 # Pin 15

GPIO.setup(FIRE_FLOW, GPIO.IN, pull_up_down=GPIO.PUD_DOWN)
GPIO.setup(HOUSE_FLOW_PULSE, GPIO.IN, pull_up_down=GPIO.PUD_DOWN)
GPIO.setup(IRRIGATION_FLOW_PULSE, GPIO.IN, pull_up_down=GPIO.PUD_DOWN)

try:
    config = configparser.ConfigParser()
    config.read('water-monitor.ini')
    p = DataPublisher()
    mqtt = MQTTClient(p,config['MQTT']['Host'],
                        int(config['MQTT']['Port']),
                        config['MQTT']['Username'],
                        config['MQTT']['Password'])
    pressureSensor = PressureSensor()
    with ExitStack() as stack:
        p.EnterContext(stack)
        stack.enter_context(mqtt)
        stack.enter_context(pressureSensor)
        while True:
            # Report values of all GPIO inputs to the DataHandler
            p.fireFlowInput(GPIO.input(FIRE_FLOW))

            p.houseFlowInput(GPIO.input(HOUSE_FLOW_PULSE))
            p.irrigationFlowInput(GPIO.input(IRRIGATION_FLOW_PULSE))

            # Read Inlet/Outlet Pressures over I2C
            p.inletPressureInput(pressureSensor.inletPressure)
            p.outletPressureInput(pressureSensor.outletPressure)

            # check inputs at 100Hz. Could use some verification here of typical
            # pulse width, or possibily use a different GPIO mode which latches
            # once a pulse is received.  We do know at maximum theoretical flow
            # for the pump (35 GPM) we will get 5.8 pulses per second, the
            # question is only how long the signal remains high, and whether
            # that will always be longer than a 10ms delay here (not accounting
            # for scheduling jitter); this depends entirely on the pulse
            # mechanism in the flow meter itself. At 100Hz, this script appears
            # to consume around 8% of the CPU.
            time.sleep(0.01)

except KeyboardInterrupt:
    GPIO.cleanup()
